import type { Metadata } from "next";
import Header from "@/components/main-site/layout/header";
import Footer from "@/components/main-site/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainSiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <section>{children}</section>
      <Footer />
    </>
  );
}
